module.exports = {
  BLACKLIST_MESSAGE: "You are not allowed to use this bot, {player}.",
  MASTER_PROTECTED_MESSAGE: "The primary master, {master}, cannot be removed.",
  MASTER_JOIN_MESSAGE: "Welcome, my master.", MASTER_LEAVE_MESSAGE: "Goodbye, my master.",
  TPA_REJECT_MESSAGE: "My master does not allow me to accept your request, {player}.",
  TELEPORT_APPROVAL_MESSAGE: "Teleport request from {player} ({type}) needs master approval. A master should reply !y or !n.",
  MASTER_ONLY_MESSAGE: "{player}, only a master can use that command.", PUBLIC_ACCESS_MESSAGE: "Bot access is now public.",
  PRIVATE_ACCESS_MESSAGE: "Bot access is now private. Only masters may use bot commands, and teleport requests require master approval.",
  TPA_USAGE_MESSAGE: "Usage: !tpa <on|off>", TPA_STATUS_MESSAGE: "Teleport requests are now {status}.",
  MASTER_USAGE_MESSAGE: "Usage: !master <username>", BLACKLIST_USAGE_MESSAGE: "Usage: !bl <username>",
  RM_BLACKLIST_USAGE_MESSAGE: "Usage: !rmbl <username>", RM_MASTER_USAGE_MESSAGE: "Usage: !rm master <username>",
  ALREADY_MASTER_MESSAGE: "{player} is already a master.", MASTER_ADDED_MESSAGE: "{player} is now a master.",
  PRIMARY_MASTER_BLACKLIST_MESSAGE: "The primary master cannot be blacklisted.", ALREADY_BLACKLISTED_MESSAGE: "{player} is already blacklisted.",
  BLACKLISTED_MESSAGE: "{player} has been blacklisted.", NOT_SECONDARY_MASTER_MESSAGE: "{player} is not a secondary master.",
  MASTER_REMOVED_MESSAGE: "{player} is no longer a master.", NOT_BLACKLISTED_MESSAGE: "{player} is not blacklisted.",
  UNBLACKLISTED_MESSAGE: "{player} has been removed from the blacklist.", UNKNOWN_MASTER_COMMAND_MESSAGE: "Unknown master command.",
  STATUS_MESSAGE: "Online for {seconds} seconds.", PRIMARY_STOP_ONLY_MESSAGE: "{player}, only the primary master can stop the bot.",
  STOP_MESSAGE: "Stopping AFK bot.", GOAL_REACHED_MESSAGE: "I reached the coordinates.", FOLLOWING_MESSAGE: "Following {player}.",
  FOLLOW_TARGET_NOT_FOUND_MESSAGE: "I cannot see you, {player}. Try !come x y z for a one-time destination.",
  COMING_COORDINATES_MESSAGE: "Coming to {coordinates}.", COMING_PLAYER_MESSAGE: "Coming to {player}.",
  COME_TARGET_NOT_FOUND_MESSAGE: "I cannot see you, {player}. Send !come x y z with your coordinates.",
  NOT_FOLLOWING_MESSAGE: "{player}, I am not following anyone.", NAVIGATION_STOPPED_MESSAGE: "Stopped following and navigation.",
  NAVIGATION_TARGET_LEFT_MESSAGE: "{player} left the server, so navigation was stopped.",
  COMMAND_HELP_GENERAL: "Commands: !status (uptime), !follow (follow you), !come [x y z] (come to you or coordinates).|Commands: !stopfollow (stop moving), !stop (stop bot; primary master only), !cmd (show commands).",
  COMMAND_HELP_MASTER: "Master: !master <name>, !rm master <name>, !bl <name>, !rmbl <name>.|Master: !public, !private, !tpa <on|off>, !y (accept request), !n (reject request).",
};
